### ISSUE TITLE
Can't open this Lab

### ISSUE THREAD

**Issue by vaibhavhrt** [learn-co-curriculum/rendering-collections-reading#14]
This lab can't be opened in either browser IDE or learn IDE. In browser "OpenIDE" option is not there and while trying to use learn ide an empty folder opens up.

**Comment by vaibhavhrt** [comment]
There are few other labs with the same issue.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
