### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/rendering-collections-reading#3]
I am getting a stranger error when I change the post_params method on posts_controller

**Comment by Lukeghenco** [comment]
![screen shot 2016-01-27 at 2 04 13 pm](https://cloud.githubusercontent.com/assets/15013243/12624789/df5a04b2-c4fe-11e5-8594-ffed4a72d402.png)

**Comment by AnnJohn** [comment]
@blake41 can you look at this?

**Comment by Lukeghenco** [comment]
Yea I tried changing post_params to be:

def post_params
  params.require(:post).permit(:title, :description)
end 

and then it showed up.

**Comment by pletcher** [comment]
This was fixed in https://github.com/learn-co-curriculum/rendering-collections-reading/commit/81f7f85641bcd9ef6c13b5adecd0577073220bb5
